# Generated by Django 5.1.1 on 2024-10-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_age_alter_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profiles/images/default_image.png', upload_to='profiles/images/'),
        ),
    ]
