# Generated by Django 5.1.1 on 2024-10-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='products/images/default.jpg', upload_to='products/images/'),
        ),
    ]
